version: '3'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  angular:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - 4300:4200
